AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - switchbot.gemspec
    - spec/**/*

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
